version: "3"

services:

  frontoffice:
    image: fonoster/goodtok-frontoffice:latest
    restart: unless-stopped
    environment:
      # Must be accessible from the browser
      API_ENDPOINT: http://localhost:6789/v1
      LOGS_LEVEL: ${LOGS_LEVEL}
    ports:
      - 8080:8080

  apiserver:
    image: fonoster/goodtok-apiserver:latest
    restart: unless-stopped
    environment:
      APP_URL: ${APP_URL}
      OWNER_EMAIL: ${OWNER_EMAIL}
      OWNER_PASSWORD: ${OWNER_PASSWORD}
      CLOAK_ENCRYPTION_KEY: ${CLOAK_ENCRYPTION_KEY}
      DATABASE_URL: ${DATABASE_URL}
      SIP_SIGNALING_SERVER: ${SIP_SIGNALING_SERVER}
      SIP_DOMAIN: ${SIP_DOMAIN}
      NATS_URL: nats:4222
      LOGS_LEVEL: ${LOGS_LEVEL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_AUTH_USER: ${SMTP_AUTH_USER}
      SMTP_AUTH_PASS: ${SMTP_AUTH_PASS}
      SMTP_SENDER: ${SMTP_SENDER}
    ports:
      - 6789:6789
    volumes:
      - ./.keys:/keys

  routr:
    image: fonoster/routr-one:latest
    restart: unless-stopped
    environment:
      EXTERNAL_ADDRS: ${DOCKER_HOST_ADDRESS}
      CONNECT_VERIFIER_PUBLIC_KEY_PATH: /keys/public.key
      NATS_PUBLISHER_ENABLED: true
      NATS_PUBLISHER_URL: nats:4222
      LOGS_LEVEL: ${LOGS_LEVEL}
    ports:
      - 5062:5062
      - 5063:5063
    volumes:
      - ./.keys/public.key:/keys/public.key

  nats:
    image: nats:latest
    restart: unless-stopped
    expose:
      - 4222

  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
      PGTZ: UTC
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
