version: "3"

services:

  frontoffice:
    build:
      context: .
      dockerfile: ./mods/frontoffice/Dockerfile

  apiserver:
    build:
      context: .
      dockerfile: ./mods/apiserver/Dockerfile
  nats:
    image: nats:latest
    ports:
      - 4222:4222

  postgres:
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8181:8080
