name: add contributors
on:
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@master
      with:
        CONTRIBUTOR: "<!--contributors:start-->"
        COLUMN_PER_ROW: "6"
        ACCESS_TOKEN: ${{secrets.GH_PAT}}
        IMG_WIDTH: "100"
        FONT_SIZE: "14"
        PATH: "/README.md"
        COMMIT_MESSAGE: "docs(README): update contributors"
        AVATAR_SHAPE: "round"
